fix(lwrunner): create ~/.ssh directory if not exist (#933)
**Summary**

This change fixes the issue where we try to add a known host to the
known_hosts file but the directory ~/.ssh does not exist.

Now we are creating that directory first.

**How did you test this change?**

Replicated the issue inside our unit tests:
```
    === Failed
    === FAIL: lwrunner TestLwRunnerAddKnownHost (0.19s)
        runner_test.go:132:
                    Error Trace:    /Users/afiune/github/go-sdk/lwrunner/runner_test.go:132
                    Error:          Received unexpected error:
                                    open /var/folders/pn/rtky3yx17fx60dc03njhm_fw0000gn/T/lwrunner1052124622/.ssh/known_hosts: no such file or directory
                    Test:           TestLwRunnerAddKnownHost
```


**Issue**

Closes https://github.com/lacework/go-sdk/issues/915
Jira https://lacework.atlassian.net/browse/ALLY-1195

Signed-off-by: Salim Afiune Maya <afiune@lacework.net>